from sqlmodel import Field, SQLModel
from typing import Optional
import datetime

class viajeroValidator(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    time: datetime = Field(default_factory=datetime.now)
    case: int
    age: int
    gender: int
    orientation: int
    heritage: int
    hispanic: int
    education: int
    travel_companions: int
    travel_companions_n: int
    origin: str
    housing_in: int
    vacations_in: bool
    business_in: bool
    family_visit_p_in: bool
    study_in: bool
    medical_tourism_in: bool
    other_in: bool
    night_life_in: bool
    purchases_in: bool
    beach_water_in: bool
    restaurants_in: bool
    concerts_in: bool
    ecotourism_in: bool
    family_visit_a_in: bool
    visit_center_municipio_in: bool
    visit_north_municipio_in: bool
    visit_northeast_municipio_in: bool
    visit_southeast_municipio_in: bool
    visit_south_municipio_in: bool
    visit_northwest_municipio_in: bool
    visit_southwest_municipio_in: bool
    visit_viequesculebra_in: bool
    other_in: bool
    knowledge_of_pr: int
    stay_length_out: int
    primary_municipio: int
    visited_municipio: int
    security: int
    expenditure_in: float
    housing_exp_in: int
    food_exp_in: int
    transport_exp_in: int
    activities_exp_in: int
    purchases_exp_in: int
    other_exp_in: int
    destination: str
    state: str
    city: str
    housing_out: int
    vacations_out: bool
    moving_out: bool
    business_out: bool
    family_visit_p_out: bool
    study_out: bool
    medical_tourism_out: bool
    other_out: bool
    night_life_out: bool
    purchases_out: bool
    restaurants_out: bool
    concerts_out: bool
    ecotourism_out: bool
    jobsearch_out: bool
    moving_prep_out: bool
    other_out: bool
    trip_length_out: int
    expenditure_out: float
    housing_exp_out: int
    food_exp_out: int
    transport_exp_out: int
    activites_exp_out: int
    purchases_exp_out: int
    other_exp_out: int
